### ISSUE TITLE
Deprecate old eslint-plugin-m6web-i18n

### ISSUE THREAD

**Issue by flepretre** [M6Web/i18n-tools#3]
The old [eslint-plugin-m6web-i18n](https://github.com/M6Web/eslint-plugin-m6web-i18n) has to be deprecated.

For that we need to:
- [x] for @m6web/eslint-plugin-i18n
  - [x] update documentation
  - [x] release a new version and publish it on npm
- [x] for [eslint-plugin-m6web-i18n](https://github.com/M6Web/eslint-plugin-m6web-i18n)
  - [x] deprecate repository in documentation
  - [x] deprecate package on npm

**Comment by Slashgear** [comment]
I am on it 🎉

**Comment by Slashgear** [comment]
Done ✅
